### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by zhengchenliang** [AlexeiSheplyakov/GiNaC#1]
Platform: Arch Linux x86_64

Issue: Building the packages from either automake or CMake, when doing "make" it appears

Traceback (most recent call last):
  File "/root/D2_math_alge/ginac_me/ginac/function.py", line 9, in <module>
    import yaptu
  File "/root/D2_math_alge/ginac_me/ginac/../scripts/yaptu.py", line 69
    exec stat in self.globals,self.locals
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'exec'. Did you mean exec(...)?
make[2]: *** [ginac/CMakeFiles/ginac.dir/build.make:81: ginac/function.h] Error 1
make[1]: *** [CMakeFiles/Makefile2:455: ginac/CMakeFiles/ginac.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by manuel5975p** [comment]
in ginac/CMakeLists.txt, replace python with python2. I made a pull request for this.
